apiVersion: apps/v1
kind: Deployment
metadata:
  name: aar-deployment
  labels:
    app: aar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aar
  template:
    metadata:
      labels:
        app: aar
    spec:
      containers:
        - name: aar
          image: emhusnan/mdd-aar-service:v0.0.1-staging
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aar-service
spec:
  selector:
    app: aar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aar-ingress
  annotations:
    plugins.konghq.com: cors
spec:
  rules:
    - host: api-staging.mdd.co.id
      http:
        paths:
          - path: /aar-service
            backend:
              serviceName: aar-service
              servicePort: 80

---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: aar-ingress
route:
  strip_path: true


