apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: emhusnan/mdd-auth-service:v0.0.1-dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    plugins.konghq.com: cors
spec:
  rules:
    - host: api-dev.mdd.co.id
      http:
        paths:
          - path: /auth-service
            backend:
              serviceName: auth-service
              servicePort: 80

---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: auth-ingress
route:
  strip_path: true

