apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment-dev
  namespace: dev
  labels:
    app: auth-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-dev
  template:
    metadata:
      labels:
        app: auth-dev
    spec:
      containers:
        - name: auth-dev
          image: emhusnan/mdd-auth-service:v0.0.2-dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-dev
  namespace: dev
spec:
  selector:
    app: auth-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth-ingress-dev
  namespace: dev
  annotations:
      kubernetes.io/ingress.class: kong
      plugins.konghq.com: dev-kong-cors
spec:
  rules:
    - host: api-dev.mdd.co.id
      http:
        paths:
          - path: /auth-service
            backend:
              serviceName: auth-service-dev
              servicePort: 80

---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: auth-ingress-dev
  namespace: dev
  annotations:
      plugins.konghq.com: cors
route:
  strip_path: true