apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2h-deployment
  labels:
    app: h2h
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2h
  template:
    metadata:
      labels:
        app: h2h
    spec:
      containers:
        - name: h2h
          image: emhusnan/mdd-h2h-service:v0.0.1-staging
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: h2h-service
spec:
  selector:
    app: h2h
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: h2h-ingress
  annotations:
    plugins.konghq.com: cors
spec:
  rules:
    - host: api-staging.mdd.co.id
      http:
        paths:
          - path: /v1/h2h
            backend:
              serviceName: h2h-service
              servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: h2h-ingress
route:
  strip_path: true

