apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-deployment
  labels:
    app: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: emhusnan/mdd-location-service:v0.0.1-staging
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  selector:
    app: location
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: location-ingress
  annotations:
    plugins.konghq.com: cors
spec:
  rules:
    - host: api-staging.mdd.co.id
      http:
        paths:
          - path: /v1/location
            backend:
              serviceName: location-service
              servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: location-ingress
route:
  strip_path: true

