apiVersion: apps/v1
kind: Deployment
metadata:
  name: unlock-aar-deployment
  labels:
    app: unlock-aar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unlock-aar
  template:
    metadata:
      labels:
        app: unlock-aar
    spec:
      containers:
        - name: unlock-aar
          image: emhusnan/mdd-unlock-aar-service:v0.0.1-staging
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: unlock-aar-service
spec:
  selector:
    app: unlock-aar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: unlock-aar-ingress
  annotations:
    plugins.konghq.com: cors
spec:
  rules:
    - host: api-staging.mdd.co.id
      http:
        paths:
          - path: /unlock-aar
            backend:
              serviceName: unlock-aar-service
              servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: unlock-aar-ingress
route:
  strip_path: true

