apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-deployment-dev
  namespace: dev
  labels:
    app: wallet-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-dev
  template:
    metadata:
      labels:
        app: wallet-dev
    spec:
      containers:
        - name: wallet
          image: emhusnan/mdd-wallet-service:v0.0.2-dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service-dev
  namespace: dev
spec:
  selector:
    app: wallet-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wallet-ingress-dev
  annotations:
    plugins.konghq.com: cors
spec:
  rules:
    - host: api-dev.mdd.co.id
      http:
        paths:
          - path: /wallet-service
            backend:
              serviceName: wallet-service
              servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: wallet-ingress-dev
route:
  strip_path: true

