apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-deployment
  labels:
    app: wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet
  template:
    metadata:
      labels:
        app: wallet
    spec:
      containers:
        - name: wallet
<<<<<<< HEAD
          image: emhusnan/mdd-wallet-service:v0.0.6-prod
=======
          image: emhusnan/mdd-wallet-service:v0.0.5-prod
>>>>>>> d29a8d4c1d4707201f3075034b9fddc48abe0aa9
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  selector:
    app: wallet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wallet-ingress
  annotations:
    plugins.konghq.com: cors
spec:
  rules:
    - host: api-prod.mdd.co.id
      http:
        paths:
          - path: /wallet-service
            backend:
              serviceName: wallet-service
              servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: wallet-ingress
route:
  strip_path: true

